[env.production]
name = "spam-checker-mcp"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[env.production.kv_namespaces]]
binding = "SPAM_CACHE"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

# Environment variables (set via wrangler secret)
# TWILIO_ACCOUNT_SID - set via: wrangler secret put TWILIO_ACCOUNT_SID
# TWILIO_AUTH_TOKEN - set via: wrangler secret put TWILIO_AUTH_TOKEN