name = "spam-check-mcp2"
main = "src/worker.js"
compatibility_date = "2024-09-23"
workers_dev = true
route = { pattern = "spam-check-mcp2.joseph-aae.workers.dev/*", zone_name = "joseph-aae.workers.dev" }

# Environment variables (set via wrangler secret)
# TWILIO_ACCOUNT_SID - set via: wrangler secret put TWILIO_ACCOUNT_SID --name spam-check-mcp2
# TWILIO_AUTH_TOKEN - set via: wrangler secret put TWILIO_AUTH_TOKEN --name spam-check-mcp2